# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'windows3.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Finish(object):
    def setupUi(self, Finish):
        Finish.setObjectName("Finish")
        Finish.resize(500, 360)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Finish.sizePolicy().hasHeightForWidth())
        Finish.setSizePolicy(sizePolicy)
        Finish.setMaximumSize(QtCore.QSize(500, 360))
        self.Next = QtWidgets.QPushButton(Finish)
        self.Next.setGeometry(QtCore.QRect(410, 320, 75, 23))
        self.Next.setObjectName("Next")
        self.label = QtWidgets.QLabel(Finish)
        self.label.setGeometry(QtCore.QRect(30, 30, 451, 91))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")

        self.retranslateUi(Finish)
        QtCore.QMetaObject.connectSlotsByName(Finish)

    def retranslateUi(self, Finish):
        _translate = QtCore.QCoreApplication.translate
        Finish.setWindowTitle(_translate("Finish", "戰艦世界 指揮官語音修改程式"))
        self.Next.setText(_translate("Finish", "完成"))
        self.label.setText(_translate("Finish", "修改完成\n"
"請注意不要開啟設定畫面否則需要再次重新修改\n"
"有任何問題請在巴哈回報"))
