# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'windows1.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Position_Check(object):
    def setupUi(self, Position_Check):
        Position_Check.setObjectName("Position_Check")
        Position_Check.resize(500, 360)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Position_Check.sizePolicy().hasHeightForWidth())
        Position_Check.setSizePolicy(sizePolicy)
        Position_Check.setMaximumSize(QtCore.QSize(500, 360))
        self.Next = QtWidgets.QPushButton(Position_Check)
        self.Next.setGeometry(QtCore.QRect(320, 320, 75, 23))
        self.Next.setObjectName("Next")
        self.Cancel = QtWidgets.QPushButton(Position_Check)
        self.Cancel.setGeometry(QtCore.QRect(410, 320, 75, 23))
        self.Cancel.setObjectName("Cancel")
        self.Position = QtWidgets.QLineEdit(Position_Check)
        self.Position.setGeometry(QtCore.QRect(40, 230, 401, 20))
        self.Position.setObjectName("Position")
        self.Text = QtWidgets.QLabel(Position_Check)
        self.Text.setGeometry(QtCore.QRect(40, 60, 381, 151))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.Text.setFont(font)
        self.Text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.Text.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.Text.setObjectName("Text")
        self.Change_Position = QtWidgets.QPushButton(Position_Check)
        self.Change_Position.setGeometry(QtCore.QRect(450, 230, 21, 23))
        self.Change_Position.setCheckable(False)
        self.Change_Position.setObjectName("Change_Position")

        self.retranslateUi(Position_Check)
        QtCore.QMetaObject.connectSlotsByName(Position_Check)

    def retranslateUi(self, Position_Check):
        _translate = QtCore.QCoreApplication.translate
        Position_Check.setWindowTitle(_translate("Position_Check", "戰艦世界 指揮官語音修改程式"))
        self.Next.setText(_translate("Position_Check", "下一步"))
        self.Cancel.setText(_translate("Position_Check", "取消"))
        self.Position.setText(_translate("Position_Check", "C:\\Games\\World_of_Warships"))
        self.Text.setText(_translate("Position_Check", "此為修改指揮官語音程式\n"
"詳情請閱讀巴哈文章\n"
"\n"
"在此請確認資料夾位置是否戰艦世界資料夾\n"
"請注意資料夾名稱應為\"World_of_Warships\"\n"
"預設是\"C:\\Games\\World_of_Warships\"\n"
""))
        self.Change_Position.setText(_translate("Position_Check", "..."))
